# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArtTap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArtTap
  pod 'Parse'
  pod 'ParseSwift'
  pod 'Parse/UI'
  pod 'DateTools'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'CHTCollectionViewWaterfallLayout/ObjC'
  pod 'Charts'
  pod 'TinyConstraints'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'STPopup'

  target 'ArtTapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtTapUITests' do
    # Pods for testing
  end

end
